# Generated by Django 2.0.1 on 2018-01-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=34)),
                ('expiration', models.DateTimeField()),
                ('openid_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OpenIdClient')),
            ],
        ),
    ]
