# Generated by Django 2.0.1 on 2018-01-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180116_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='extras',
            new_name='extra',
        ),
    ]
