# Generated by Django 2.0.1 on 2018-01-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidclient',
            name='issuer',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='openidclient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
