# Generated by Django 2.0.2 on 2018-02-08 14:44

from django.db import migrations, models
import openlobby.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180208_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='expiration',
            field=models.IntegerField(default=openlobby.core.models.get_login_attempt_expiration),
        ),
    ]
