# Generated by Django 2.0.2 on 2018-02-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180217_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_collision_id',
            field=models.IntegerField(default=0),
        ),
    ]
