# Generated by Django 2.0.2 on 2018-02-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_has_colliding_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
